image: salesforce/salesforcedx:latest-full

stages:
  - test
  - deploy

unit-test-job:
  stage: test
  script:
    - sfdx force:org:create -f project-scratch-def.json -a testingScratchOrg --setdefaultusername
    - sfdx force:source:deploy --sourcepath force-app --targetusername testingScratchOrg
    - sfdx force:apex:test:run --classnames "BeforeInsertCaseHandlerServiceTest" --resultformat tap --codecoverage --targetusername testingScratchOrg


deploy-job:
  stage: deploy
  script:
    - sfdx force:config:set instanceUrl=$InstanceUrl
    - sfdx force:source:deploy --sourcepath force-app --targetusername $OrgToken
