image: salesforce/salesforcedx:latest-full

stages:
  - test
  - deploy


deploy-to-test-org:
  stage: test
  script:
    - sfdx force:config:set instanceUrl=$InstanceUrl
    - sfdx force:source:deploy --sourcepath force-app --targetusername $OrgToken

unit-test-job:
  stage: test
  script:
    - sfdx force:apex:test:run --classnames "BeforeInsertCaseHandlerServiceTest" --resultformat tap --codecoverage --targetusername $OrgToken


deploy-job:
  stage: deploy
  script:
    - sfdx force:config:set instanceUrl=$InstanceUrl
    - sfdx force:source:deploy --sourcepath force-app --targetusername $OrgToken