/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 03-20-2022
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
public  class EventBookingConfiguration {

    public static final String WEB_SERVICE_NC = 'NC/animals';
    public static final String EMAIL_SERVICE_SENDER = 'default';
    public static final String E2C_EMAIL_TEMPLATE = 'SupportCaseCreatedWebInquiries';
    public static final String ORG_WIDE_EMAIL_ADDRESS = 'Support';

}